Use new deploy manager script

diff --git a/deploy/manage b/deploy/manage
--- a/deploy/manage
+++ b/deploy/manage
@@ -1,86 +1,81 @@
 #!/usr/bin/env bash
 
-# Use this as a wrapper around nixops. It assumes you are keeping your deployment state in the
-# repository in the same directory as this script. The deployment state files must be named
-# "{deployment}.nixops-exported" and be the result of running "nixops export -d {deployment}."
-# This means that each exported file's name must match the name of the deployment and it can only
-# contain one deployment.
+# A NixOps Wrapper for Git Projects
+# ---------------------------------
 #
-# This wrapper will automatically import these files and keep them in-sync with any nixops actions
-# you do *with this script*.
+# This tool is a simple wrapper around NixOps. The goal is to make it easier to use NixOps when you
+# want to share your deployment state between members of a team.
 #
-# A temporary state file is kept behind the scenes.
+# To achieve this, this wrapper gives every deployment as a separate state file which is placed
+# in the same directory as this script. The files have the `.nixops` extension.
 #
-# This script supports some "meta-commands" (i.e. commands that don't get proxied to nixops):
-#   * "./manage .clear" will clear the temporary state file. This is useful after pulling updates
-#                       and your current state file isn't in sync.
-#   * "/.manage .shell" will drop you into a nix-shell but with the exact same environment as your
-#                       deployment system. It's safe to use `nixops` in this shell.
+# You are expected to keep these files in version control. It's also *highly* recommended that you
+# use a tool like git-crypt to keep them encrypted with this entry in .gitattributes:
+#
+#    *.nixops   binary filter=git-crypt diff=git-crypt
+#
+# This tool also enforces a per-repository version of Nixpkgs via a `nixpkgs-version.sh` file in the
+# same directory as the script. This ensures that all users have a consistent version of NixOps and
+# deploy a consistent set of packages to servers.
+#
+# Most commands work identically to NixOps. However, instead of specifying deployments with
+# the `--deployment/-d` flag, you select a deployment in the first argument. In other words, instead
+# of the normal NixOps usage of
+#
+#   nixops deploy -d stage --check  # Normal nixops usage.
+#
+# You'd run:
+#
+#   ./manage stage deploy --check   # Manage script usage.
+#
+# This assume there is a file ./stage.nixops where this state is being stored.
+#
+# Use `./manage --help` to see normal NixOps help.
+# Use `./manage {deployment} .shell` to open a Nix shell where the environment is set up to use
+# `nixops` directly with the same behavior as running `./manage` commands.
 
 set -e
 
+# Check for Nix tools.
+command -v nix-shell >/dev/null 2>&1 || {
+  nix_profile="$HOME/.nix-profile/etc/profile.d/nix.sh"
+  if [ -e "$nix_profile" ]; then
+    source "$nix_profile"
+  else
+    >&2 echo "Failed to find 'nix-shell' on PATH or a Nix profile to load. Have you installed Nix?"
+    exit 1
+  fi
+}
+
 repo_root=$(git rev-parse --show-toplevel)
-
 here=$(dirname "$0")
-cd "$here"
 
-state_file=".deployments.nixops"
+deployment="$1"
+command="$2"
+state_file="$here/${deployment}.nixops"
 
-if [ "$1" == ".clear" ]; then
-  echo Clearing "$here/$state_file"
-  rm "$state_file"
-  exit 0
-fi
-
-source nixpkgs-version.sh
+source "$here/nixpkgs-version.sh"
 
 export NIX_PATH=nixpkgs="$nixpkgs_snapshot":"$repo_root":.
 export NIXOPS_STATE="$state_file"
+export NIXOPS_DEPLOYMENT="$deployment"
 
-export withNixops="nix-shell -p $nixops_version --run"
+withNixops="nix-shell -p $nixops_version --run"
 
-nixops_export_files=$(find . -maxdepth 1 -name '*.nixops-exported' -print)
+# Arg list trick:
+# https://stackoverflow.com/questions/3104209
+# ARGS=$(printf "%q"" " "$@")
 
-if ! [ -f "$state_file" ] && [ -n "$nixops_export_files" ]; then
-  echo "State file needs to be initialized. Run \"$0 clear\" to clear it after a merge or checkout."
-
-  for file in $nixops_export_files; do
-    echo "Importing $file"
-    $withNixops "nixops import" < "$file"
-  done
-fi
-
-update_export_file() {
-  file="$1"
-  depl=$(basename "${file%.*}")
-
-  tmp_file="$file.tmp"
-  if $withNixops "nixops export -d $depl > $tmp_file"; then
-    mv "$tmp_file" "$file"
-    echo "Updated $depl at $file"
-  else
-    >&2 echo "Failed to update $depl at $file"
-    rm -f "$tmp_file"
-  fi
-}
-
-update_exports() {
-  if [ -n "$nixops_export_files" ]; then
-    for file in $nixops_export_files; do
-      update_export_file "$file"
-    done
-  fi
-}
-
-# IMPORTANT: exported state must always match the state file, so run this regardless of exit path
-trap update_exports EXIT
-
-if [ "$1" == ".shell" ]; then
-  nix-shell -p "$nixops_version"
-else
-  # Arg list trick:
-  # https://stackoverflow.com/questions/3104209
+if [[ $deployment == --* ]]; then
   ARGS=$(printf "%q"" " "$@")
-
+  $withNixops "nixops $ARGS"
+  exit $?
+elif [ "$command" == ".shell" ]; then
+  nix-shell -p "$nixops_version"
+elif [ ! -e "$state_file" ]; then
+  >&2 echo "You're trying to use a deployment that doesn't exist yet. Try running $0 $deployment create"
+  exit 1
+else
+  ARGS=$(printf "%q"" " "${@:2}")
   $withNixops "nixops $ARGS"
 fi
